# BTU-Fuel Calculator

def Input():
    try:
        fuel_amount = int(input("Fuel amount => "))
        energy_rate = 5.8e6/42
        efficiency = int(input("Energy efficiency => "))/100
        result = (fuel_amount*energy_rate*efficiency)
    except:
        print("Try again!")
        Input()
    else:
        print("Total energy may generated by the fuel is {} BTU".format(result))

Input()